//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBSysProj.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class CheckOut
    {
        public int coId { get; set; }
        public Nullable<int> roomId { get; set; }
        public string coFirstName { get; set; }
        public string coLastName { get; set; }
        public string coAddress { get; set; }
        public string coEmail { get; set; }
        public string coPhone { get; set; }
        public Nullable<System.DateTime> coCheckIn { get; set; }
        public Nullable<System.DateTime> coCheckOut { get; set; }
        public Nullable<int> coPayment { get; set; }
        public Nullable<int> coBalance { get; set; }
        public Nullable<int> bookedBy { get; set; }
    
        public virtual Rooms Rooms { get; set; }
        public virtual UserAccount UserAccount { get; set; }
    }
}
