//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBSysProj.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rooms
    {
        public Rooms()
        {
            this.CheckOut = new HashSet<CheckOut>();
        }
    
        public int roomId { get; set; }
        public string roomNumber { get; set; }
        public string roomType { get; set; }
        public string roomAc { get; set; }
        public Nullable<int> roomBed { get; set; }
        public Nullable<int> roomMin { get; set; }
        public Nullable<int> roomMax { get; set; }
        public Nullable<int> roomPrice { get; set; }
        public Nullable<int> hotelId { get; set; }
        public string isAvailable { get; set; }
    
        public virtual ICollection<CheckOut> CheckOut { get; set; }
        public virtual Hotel Hotel { get; set; }
    }
}
