//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBSysProj.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_AllRooms
    {
        public int Room_Id { get; set; }
        public string Room_Number { get; set; }
        public string Room_Type { get; set; }
        public string Aircon { get; set; }
        public Nullable<int> Bed { get; set; }
        public Nullable<int> Minimum_Guest { get; set; }
        public Nullable<int> Maximum_Guest { get; set; }
        public Nullable<int> Price { get; set; }
        public Nullable<int> Hotel_Id { get; set; }
        public string Hotel { get; set; }
        public string Hotel_Address { get; set; }
    }
}
