//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBSysProj.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_CheckOutTable
    {
        public int Id { get; set; }
        public Nullable<int> Room_Id { get; set; }
        public string Room_Number { get; set; }
        public string Room_Type { get; set; }
        public string Aircon { get; set; }
        public Nullable<int> Bed { get; set; }
        public Nullable<int> Minimum_Guest { get; set; }
        public Nullable<int> Maximum_Guest { get; set; }
        public Nullable<int> Price { get; set; }
        public Nullable<int> Hotel_Id { get; set; }
        public string Hotel_Name { get; set; }
        public string Hotel_Address { get; set; }
        public string Available { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public string Email { get; set; }
        public string Phone_Number { get; set; }
        public Nullable<System.DateTime> Check_In { get; set; }
        public Nullable<System.DateTime> Check_Out { get; set; }
        public Nullable<int> Payment { get; set; }
        public Nullable<int> Balance { get; set; }
        public Nullable<int> Booked_By_Id { get; set; }
        public string Booked_by_Name { get; set; }
    }
}
